/**
 * Created by Wayuki on 26-Feb-17.
 */

export const CONTAINER_ACTION = {
  SET_NOTIFICATION: 'SET_CONTAINER_NOTIFICATION',
  CLOSE_NOTIFICATION: 'CLOSE_CONTAINER_NOTIFICATION',
};

export const APP_ACTION = {
};

export const SIGN_UP_ACTION = {
  TOGGLE_PROCESSING: 'TOGGLE_SIGN_UP_FORM_PROCESSING',
  HANDLE_FORM_FIELD_CHANGE: 'HANDLE_SIGN_UP_FORM_FIELD_CHANGE',
  HANDLE_FORM_SUBMIT: 'HANDLE_SIGN_UP_FORM_SUBMIT',
  SET_ERROR_MESSAGE: 'SET_SIGN_UP_FORM_ERROR_MESSAGE',
  RESET_FORM: 'RESET_SIGN_UP_FORM',
};

export const LOGIN_ACTION = {
  TOGGLE_PROCESSING: 'TOGGLE_LOGIN_FORM_PROCESSING',
  HANDLE_FORM_FIELD_CHANGE: 'HANDLE_LOGIN_FORM_FIELD_CHANGE',
  HANDLE_FORM_SUBMIT: 'HANDLE_LOGIN_FORM_SUBMIT',
  SET_ERROR_MESSAGE: 'SET_LOGIN_FORM_ERROR_MESSAGE',
  RESET_FORM: 'RESET_LOGIN_FORM',
};

export default {};
